### ISSUE TITLE
Packman to MetadataGen/GAPIC tracking issue

### ISSUE THREAD

**Issue by geigerj** [googleapis/gapic-generator#803]
This is a parent issue to track tasks related to porting the functionality of Packman to MetadataGen or GAPIC.

_Add more tasks for other languages here, or check off tasks not applicable to particular languages_

- [x] Python gRPC package generation
- [x] Python GAPIC package metadata generation
- [ ] Python common protos generation
- [ ] Java gRPC package generation
- [ ] Java GAPIC package metadata generation
- [ ] Java common protos generation
- [ ] Ruby gRPC package generation
- [ ] Ruby GAPIC package metadata generation
- [ ] Ruby common protos generation
- [x] PHP gRPC package generation
- [x] PHP GAPIC package metadata generation
- [x] PHP common protos generation
- [ ] NodeJS gRPC package generation
- [ ] NodeJS GAPIC package metadata generation
- [x] ~NodeJS GAPIC package metadata generation~ _N/A_

**Comment by garrettjonesgoogle** [comment]
So if I was going to migrate generation of grpc packages in Java to toolkit, would that fall under this issue?

**Comment by geigerj** [comment]
Yes, I had intended to use this issue as a checklist for all of the languages that use Packman, but forgot to finish filling out the list. I'll do that now.

**Comment by eoogbe** [comment]
@geigerj Can you add a priority?

**Comment by hzyi-google** [comment]
Obsolete.
